---
ui:
  replicaCount: 2
  image:
    repository: mreferre/yelb-ui
    tag: "0.7"
    pullPolicy: IfNotPresent

appserver:
  replicaCount: 2
  image:
    repository: mreferre/yelb-appserver
    tag: "0.5"
    pullPolicy: IfNotPresent

db:
  replicaCount: 1
  image:
    repository: mreferre/yelb-db
    tag: "0.5"
    pullPolicy: IfNotPresent

redis:
  replicaCount: 2
  image:
    repository: redis
    tag: "4.0.2"
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: http01-clusterissuer
  tls:
    - hosts:
        - s060709.online
      secretName: domain-name-secret
  hosts:
    - host: s060709.online
      paths:
        - path: /
          pathType: Prefix

clusterissuer:
  email: rizovoyb@yandex.ru