---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yelb
{{- if .Values.ingress.annotations}}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: http01-clusterissuer
{{ end -}}
spec:
  tls:
    {{- range .Values.ingress.tls}}
    - hosts: {{ .host }}
      secretName: {{.secretName}}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts}}
    - host: {{.host}}
      http:
        paths:
          {{- range .paths}}
          - path: {{ .path }}
            pathType: {{.pathType}}
            backend:
              service:
                name: yelb-ui
                port:
                  number: 80
          {{- end}}
    {{- end}}
