---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cicd.serviceAccount }}
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.cicd.clusterRole.name }}
rules:
  {{- toYaml .Values.cicd.clusterRole.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.cicd.clusterRole.name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.cicd.serviceAccount }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.cicd.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io