name: Helm Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.3

      - name: Run Helm Lint
        run: helm lint ./deployments/helm