name: Helm Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.2

      - name: Run Helm Lint
        run: helm lint ./deployments/helm